/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zero_licht_ffmpeg_video_utils */

#ifndef _Included_com_zero_licht_ffmpeg_video_utils
#define _Included_com_zero_licht_ffmpeg_video_utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zero_licht_ffmpeg_video_utils
 * Method:    like
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zero_licht_ffmpeg_video_1utils_like
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
